"""

Revision ID: 00f0ce4ab1b8
Revises: b91793d04891
Create Date: 2024-05-03 14:01:21.990967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00f0ce4ab1b8'
down_revision = 'b91793d04891'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
