"""

Revision ID: 3d64f40b2909
Revises: 69b935e9a79f
Create Date: 2024-05-03 16:36:16.879572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d64f40b2909'
down_revision = '69b935e9a79f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
