"""

Revision ID: 69b935e9a79f
Revises: 00f0ce4ab1b8
Create Date: 2024-05-03 16:24:22.529895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69b935e9a79f'
down_revision = '00f0ce4ab1b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jb_bot', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jb_bot', 'status')
    # ### end Alembic commands ###
