"""

Revision ID: dc193883056d
Revises: 3d64f40b2909
Create Date: 2024-05-10 14:57:09.055755

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dc193883056d'
down_revision = '3d64f40b2909'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grievance_category_test_data')
    op.add_column('jb_channel', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('jb_message', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint('jb_message_channel_id_fkey', 'jb_message', type_='foreignkey')
    op.drop_column('jb_message', 'channel_id')
    op.add_column('jb_turn', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jb_turn', 'created_at')
    op.add_column('jb_message', sa.Column('channel_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('jb_message_channel_id_fkey', 'jb_message', 'jb_channel', ['channel_id'], ['id'])
    op.drop_column('jb_message', 'created_at')
    op.drop_column('jb_channel', 'created_at')
    op.create_table('grievance_category_test_data',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ministry', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('subcategory', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fields', postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())), autoincrement=False, nullable=True),
    sa.Column('persona', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='grievance_category_test_data_pkey')
    )
    # ### end Alembic commands ###
